import './lq-form'
import './vuetify'
import './axios'
import './vuejs-object-helper'
import './lq-vuetify'
import './moment'
import './lq-v-file'
import './lq-v-datatable'
// import './socket-io'
// import './vue-nestable'
// import './vuetify-snackbar-queue'
// import Vue from 'vue'
// import ConfirmAction from '../mixins/confirm-and-action'
// import Developer from '../mixins/is-developer'
// Vue.mixin(ConfirmAction)
// Vue.mixin(Developer)